#ifndef HCS_MODEL_H
#define HCS_MODEL_H

/* Auto-generated by export_hcs_model_to_c.py. DO NOT EDIT. */

typedef enum {
    HCS_STATE_LOW,
    HCS_STATE_NO_CACHE,
    HCS_STATE_XXHIGH,
    HCS_STATE_COUNT
} hcs_state_t;

#define HCS_NQUANT 4
extern const double hcs_quantiles[HCS_NQUANT];  /* {0.5, 0.7, 0.8, 0.9} */

/* q_idx = -1 -> mean; 0..HCS_NQUANT-1 -> conservative quantile prediction (us) */
double hcs_predict_decode(hcs_state_t state, double TBS, double mcs, double nb_rb,
                          double nb_symbol, double round, int CodeBlocks, int q_idx);
double hcs_predict_frontend(hcs_state_t state, double nb_rb, int nb_symbol, int q_idx);
double hcs_predict_total(hcs_state_t state, double TBS, double mcs, double nb_rb,
                         double nb_symbol, double round, int CodeBlocks, int q_idx);
hcs_state_t hcs_state_from_name(const char *name);
const char *hcs_state_name(hcs_state_t state);

#endif /* HCS_MODEL_H */
