#!/usr/bin/env python3
"""
B: 把 hcs_model.json (UnifiedLatencyPredictor) 导出为可部署的 C 代码 (hcs_model.h/.c).

生成的 API (供 OAI gNB_scheduler_ulsch.c 调用):
  hcs_predict_decode  (state, TBS,mcs,nb_rb,nb_symbol,round, CodeBlocks, q_idx)
  hcs_predict_frontend(state, nb_rb, nb_symbol, q_idx)
  hcs_predict_total   (state, TBS,mcs,nb_rb,nb_symbol,round, CodeBlocks, q_idx)  = front + dec
  q_idx: -1 取 mean; [0,HCS_NQUANT) 取对应分位 (hcs_quantiles[]) 的保守预测.

推理逻辑与 hcs_latency_predictor.predict_module_one 完全一致 (grouped-linear + global 回退).
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

# 固定特征顺序 (与 hcs_latency_predictor 的 module 配置一致, C 端硬编码依赖此顺序)
DECODE_FEATURES = ["TBS", "mcs", "nb_rb", "nb_symbol", "round"]
DECODE_GLOBAL = ["CodeBlocks"] + DECODE_FEATURES
FRONTEND_FEATURES = ["nb_rb"]
FRONTEND_GLOBAL = ["nb_symbol"] + FRONTEND_FEATURES


def cd(x: float) -> str:
    if isinstance(x, str):
        x = float(x)
    if math.isnan(x):
        return "NAN"
    return f"{float(x):.17g}"


def state_enum(name: str) -> str:
    return "HCS_STATE_" + "".join(ch if (ch.isalnum() or ch == "_") else "_" for ch in name.upper())


def _qlist(model: dict, quantiles: list[float]) -> list[str]:
    return [cd(model["q"][f"{q:g}"]) for q in quantiles]


def _coef_in_order(coef: dict, order: list[str]) -> list[str]:
    return [cd(coef[f]) for f in order]


def gen_header(states: list[str], quantiles: list[float]) -> str:
    L = ["#ifndef HCS_MODEL_H", "#define HCS_MODEL_H", "",
         "/* Auto-generated by export_hcs_model_to_c.py. DO NOT EDIT. */", ""]
    L.append("typedef enum {")
    for s in states:
        L.append(f"    {state_enum(s)},")
    L.append("    HCS_STATE_COUNT")
    L.append("} hcs_state_t;")
    L.append("")
    L.append(f"#define HCS_NQUANT {len(quantiles)}")
    L.append("extern const double hcs_quantiles[HCS_NQUANT];  /* {" +
             ", ".join(f"{q:g}" for q in quantiles) + "} */")
    L.append("")
    L.append("/* q_idx = -1 -> mean; 0..HCS_NQUANT-1 -> conservative quantile prediction (us) */")
    L.append("double hcs_predict_decode(hcs_state_t state, double TBS, double mcs, double nb_rb,")
    L.append("                          double nb_symbol, double round, int CodeBlocks, int q_idx);")
    L.append("double hcs_predict_frontend(hcs_state_t state, double nb_rb, int nb_symbol, int q_idx);")
    L.append("double hcs_predict_total(hcs_state_t state, double TBS, double mcs, double nb_rb,")
    L.append("                         double nb_symbol, double round, int CodeBlocks, int q_idx);")
    L.append("hcs_state_t hcs_state_from_name(const char *name);")
    L.append("const char *hcs_state_name(hcs_state_t state);")
    L.append("")
    L.append("#endif /* HCS_MODEL_H */")
    return "\n".join(L) + "\n"


def gen_source(payload: dict) -> str:
    states = payload["states"]
    quantiles = payload["quantiles"]
    nq = len(quantiles)
    models = payload["models"]

    L = ['#include "hcs_model.h"', "#include <string.h>", "",
         "/* Auto-generated by export_hcs_model_to_c.py. DO NOT EDIT. */", ""]
    L.append("const double hcs_quantiles[HCS_NQUANT] = {" + ", ".join(cd(q) for q in quantiles) + "};")
    L.append("")
    # structs
    L.append(f"typedef struct {{ int key; double intercept; double coef[{len(DECODE_FEATURES)}]; "
             f"double q[HCS_NQUANT]; }} hcs_decode_group_t;")
    L.append(f"typedef struct {{ int n_groups; const hcs_decode_group_t *groups; double g_intercept; "
             f"double g_coef[{len(DECODE_GLOBAL)}]; double g_q[HCS_NQUANT]; }} hcs_decode_model_t;")
    L.append(f"typedef struct {{ int key; double intercept; double coef[{len(FRONTEND_FEATURES)}]; "
             f"double q[HCS_NQUANT]; }} hcs_frontend_group_t;")
    L.append(f"typedef struct {{ int n_groups; const hcs_frontend_group_t *groups; double g_intercept; "
             f"double g_coef[{len(FRONTEND_GLOBAL)}]; double g_q[HCS_NQUANT]; }} hcs_frontend_model_t;")
    L.append("")

    def emit_groups(state: str, module: str, features: list[str], struct: str, var: str) -> None:
        m = models[state][module]
        groups = m["groups"]
        L.append(f"static const {struct} {var}[] = {{")
        for key in sorted(groups, key=lambda k: int(k)):
            g = groups[key]
            coef = ", ".join(_coef_in_order(g["coef"], features))
            q = ", ".join(_qlist(g, quantiles))
            L.append(f"    {{ {int(key)}, {cd(g['intercept'])}, {{ {coef} }}, {{ {q} }} }},")
        L.append("};")

    # decode groups + model table
    for s in states:
        emit_groups(s, "decode", DECODE_FEATURES, "hcs_decode_group_t", f"decode_groups_{state_enum(s)}")
    L.append("")
    L.append("static const hcs_decode_model_t hcs_decode_models[HCS_STATE_COUNT] = {")
    for s in states:
        g = models[s]["decode"]["global"]
        gcoef = ", ".join(_coef_in_order(g["coef"], DECODE_GLOBAL))
        gq = ", ".join(_qlist(g, quantiles))
        var = f"decode_groups_{state_enum(s)}"
        L.append(f"    {{ (int)(sizeof({var})/sizeof({var}[0])), {var}, {cd(g['intercept'])}, "
                 f"{{ {gcoef} }}, {{ {gq} }} }},")
    L.append("};")
    L.append("")

    # frontend groups + model table
    for s in states:
        emit_groups(s, "frontend", FRONTEND_FEATURES, "hcs_frontend_group_t",
                    f"frontend_groups_{state_enum(s)}")
    L.append("")
    L.append("static const hcs_frontend_model_t hcs_frontend_models[HCS_STATE_COUNT] = {")
    for s in states:
        g = models[s]["frontend"]["global"]
        gcoef = ", ".join(_coef_in_order(g["coef"], FRONTEND_GLOBAL))
        gq = ", ".join(_qlist(g, quantiles))
        var = f"frontend_groups_{state_enum(s)}"
        L.append(f"    {{ (int)(sizeof({var})/sizeof({var}[0])), {var}, {cd(g['intercept'])}, "
                 f"{{ {gcoef} }}, {{ {gq} }} }},")
    L.append("};")
    L.append("")

    # predict functions
    L.append("""double hcs_predict_decode(hcs_state_t state, double TBS, double mcs, double nb_rb,
                          double nb_symbol, double round, int CodeBlocks, int q_idx)
{
    if (state < 0 || state >= HCS_STATE_COUNT) return 0.0;
    const hcs_decode_model_t *M = &hcs_decode_models[state];
    for (int i = 0; i < M->n_groups; i++) {
        if (M->groups[i].key == CodeBlocks) {
            const hcs_decode_group_t *g = &M->groups[i];
            double v = g->intercept + g->coef[0]*TBS + g->coef[1]*mcs + g->coef[2]*nb_rb
                       + g->coef[3]*nb_symbol + g->coef[4]*round;
            if (q_idx >= 0 && q_idx < HCS_NQUANT) v += g->q[q_idx];
            return v;
        }
    }
    /* global fallback, coef order: CodeBlocks,TBS,mcs,nb_rb,nb_symbol,round */
    double v = M->g_intercept + M->g_coef[0]*CodeBlocks + M->g_coef[1]*TBS + M->g_coef[2]*mcs
               + M->g_coef[3]*nb_rb + M->g_coef[4]*nb_symbol + M->g_coef[5]*round;
    if (q_idx >= 0 && q_idx < HCS_NQUANT) v += M->g_q[q_idx];
    return v;
}

double hcs_predict_frontend(hcs_state_t state, double nb_rb, int nb_symbol, int q_idx)
{
    if (state < 0 || state >= HCS_STATE_COUNT) return 0.0;
    const hcs_frontend_model_t *M = &hcs_frontend_models[state];
    for (int i = 0; i < M->n_groups; i++) {
        if (M->groups[i].key == nb_symbol) {
            const hcs_frontend_group_t *g = &M->groups[i];
            double v = g->intercept + g->coef[0]*nb_rb;
            if (q_idx >= 0 && q_idx < HCS_NQUANT) v += g->q[q_idx];
            return v;
        }
    }
    /* global fallback, coef order: nb_symbol,nb_rb */
    double v = M->g_intercept + M->g_coef[0]*nb_symbol + M->g_coef[1]*nb_rb;
    if (q_idx >= 0 && q_idx < HCS_NQUANT) v += M->g_q[q_idx];
    return v;
}

double hcs_predict_total(hcs_state_t state, double TBS, double mcs, double nb_rb,
                         double nb_symbol, double round, int CodeBlocks, int q_idx)
{
    return hcs_predict_frontend(state, nb_rb, (int)nb_symbol, q_idx)
         + hcs_predict_decode(state, TBS, mcs, nb_rb, nb_symbol, round, CodeBlocks, q_idx);
}
""")

    # name <-> enum helpers
    L.append("hcs_state_t hcs_state_from_name(const char *name)")
    L.append("{")
    for s in states:
        L.append(f'    if (strcmp(name, "{s}") == 0) return {state_enum(s)};')
    L.append("    return HCS_STATE_COUNT;")
    L.append("}")
    L.append("")
    L.append("const char *hcs_state_name(hcs_state_t state)")
    L.append("{")
    L.append("    switch (state) {")
    for s in states:
        L.append(f'        case {state_enum(s)}: return "{s}";')
    L.append('        default: return "UNKNOWN";')
    L.append("    }")
    L.append("}")
    return "\n".join(L) + "\n"


def validate(payload: dict) -> None:
    for s in payload["states"]:
        d = payload["models"][s]["decode"]
        f = payload["models"][s]["frontend"]
        if d["features"] != DECODE_FEATURES or d["group_col"] != "CodeBlocks":
            raise ValueError(f"decode feature/group mismatch in state {s}: {d['features']}/{d['group_col']}")
        if f["features"] != FRONTEND_FEATURES or f["group_col"] != "nb_symbol":
            raise ValueError(f"frontend feature/group mismatch in state {s}: {f['features']}/{f['group_col']}")


def main() -> None:
    ap = argparse.ArgumentParser(description="export hcs_model.json -> hcs_model.h/.c")
    ap.add_argument("--in-json", default="python_scripts/hcs_model_out/hcs_model.json")
    ap.add_argument("--out-dir", default="python_scripts/hcs_model_out")
    args = ap.parse_args()

    payload = json.loads(Path(args.in_json).read_text(encoding="utf-8"))
    validate(payload)
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "hcs_model.h").write_text(gen_header(payload["states"], payload["quantiles"]), encoding="utf-8")
    (out / "hcs_model.c").write_text(gen_source(payload), encoding="utf-8")

    n_groups = {s: {m: len(payload["models"][s][m]["groups"]) for m in ("decode", "frontend")}
                for s in payload["states"]}
    print(f"states={payload['states']} quantiles={payload['quantiles']}")
    print(f"groups per state: {n_groups}")
    print(f"wrote: {out / 'hcs_model.h'}\n       {out / 'hcs_model.c'}")


if __name__ == "__main__":
    main()
