#!/usr/bin/env python3
"""
把两个 FFT state 分类模型导出成一个**运行时可切换**的 C 分类器 (plan 组件 ③/2a):
  - mode A = HCS_CLF_MEAN_THRESHOLD : 单特征窗口均值 + 3 阈值 digitize (train_fft_latency_state_classifier.py)
  - mode B = HCS_CLF_TREE           : 窗口 [mean,std,skew,kurt] 浅决策树 (train_fft_tree_classifier.py)
两版共用同一环形缓冲与窗口特征计算; 通过 hcs_fft_classifier_t.mode 切换, 便于调试对比.

C 端窗口特征与 Python (fft_feature_moment_experiment.window_features / add_fft_features 的 fft_mean) 一致:
  mean = 窗口均值; std = sqrt(E[(x-mean)^2]); skew = E[d^3]/m2^1.5; kurt = E[d^4]/m2^2 - 3 (expanding window 起步).
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

INTERF_ORDER = ["NO_CACHE", "LOW", "MED", "XXHIGH"]
TREE_FEATURES = ["mean", "std", "skew", "kurt"]   # C feats[] 顺序; 必须与 tree feature_order 一致


def cd(x: float) -> str:
    return f"{float(x):.17g}"


def parse_window(feature: str) -> int:
    m = re.fullmatch(r"fft_(mean|median|p90|max)_w(\d+)", feature)
    if not m:
        raise ValueError(f"unsupported threshold feature: {feature}")
    if int(m.group(2)) > 1 and m.group(1) != "mean":
        raise ValueError(f"C mode A 仅支持 fft_mean_wW (got {feature})")
    return int(m.group(2))


def state_enum(name: str) -> str:
    return "HCS_STATE_" + name.upper()


def map_interf_to_state(interf: str, predictor_states: list[str]) -> str:
    if interf in predictor_states:
        return interf
    hi = INTERF_ORDER.index(interf)
    for cand in INTERF_ORDER[hi + 1:]:
        if cand in predictor_states:
            return cand
    for cand in reversed(INTERF_ORDER[:hi]):
        if cand in predictor_states:
            return cand
    return predictor_states[0]


def gen_header(window: int) -> str:
    return f"""/* hcs_state_classifier.h —— Auto-generated by export_fft_classifier_to_c.py. DO NOT EDIT.
 * FFT 时延 -> 争用 state 分类器 (plan 组件 ③/2a). 两版运行时可切换 (见 hcs_clf_mode_t).
 */
#ifndef HCS_STATE_CLASSIFIER_H
#define HCS_STATE_CLASSIFIER_H

#include "hcs_model.h"   /* hcs_state_t */

#ifdef __cplusplus
extern "C" {{
#endif

enum {{ HCS_INTERF_NO_CACHE = 0, HCS_INTERF_LOW = 1, HCS_INTERF_MED = 2,
       HCS_INTERF_XXHIGH = 3, HCS_INTERF_COUNT = 4 }};

/* 运行时可切换的分类方法 */
typedef enum {{
  HCS_CLF_MEAN_THRESHOLD = 0,   /* mode A: 窗口均值 + 阈值 */
  HCS_CLF_TREE           = 1    /* mode B: [mean,std,skew,kurt] 浅决策树 */
}} hcs_clf_mode_t;

#define HCS_FFT_WINDOW {window}

typedef struct {{
  double buf[HCS_FFT_WINDOW];   /* 最近 W 个 slot 的 FFT 时延 (µs) */
  int next_idx;                 /* 下一个写入位置 (单调递增取模) */
  int count;                    /* 已填入样本数 (<= W) */
  hcs_clf_mode_t mode;          /* 当前分类方法; 可随时切换对比 */
}} hcs_fft_classifier_t;

typedef struct {{ double mean, std, skew, kurt; }} hcs_fft_feats_t;

void            hcs_classifier_init(hcs_fft_classifier_t *c, hcs_clf_mode_t mode);
void            hcs_classifier_set_mode(hcs_fft_classifier_t *c, hcs_clf_mode_t mode);
void            hcs_classifier_push(hcs_fft_classifier_t *c, double fft_us);  /* 每 slot 推入 */
hcs_fft_feats_t hcs_classifier_feats(const hcs_fft_classifier_t *c);          /* 窗口矩特征 */
int             hcs_classifier_interf_mode(const hcs_fft_classifier_t *c, hcs_clf_mode_t mode);
int             hcs_classifier_interf(const hcs_fft_classifier_t *c);   /* 按 c->mode 分发; 空->-1 */
const char     *hcs_interf_name(int interf);
const char     *hcs_clf_mode_name(hcs_clf_mode_t mode);
hcs_state_t     hcs_interf_to_state(int interf);   /* 4-class -> 预测器 3-state */

#ifdef __cplusplus
}}
#endif

#endif /* HCS_STATE_CLASSIFIER_H */
"""


def gen_source(thresholds: list[float], tree: dict, predictor_states: list[str]) -> str:
    t = ", ".join(cd(x) for x in thresholds)
    n = tree["n_nodes"]

    def arr(name, vals, fmt):
        return f"static const {name} = {{ " + ", ".join(fmt(v) for v in vals) + " };"

    L = ['/* hcs_state_classifier.c —— Auto-generated by export_fft_classifier_to_c.py. DO NOT EDIT. */',
         '#include "hcs_state_classifier.h"', "#include <math.h>", ""]
    L.append(f"static const double HCS_FFT_THRESHOLDS[3] = {{ {t} }};")
    L.append("")
    L.append(f"/* mode B: 浅决策树 (feats order = {tree['feature_order']}), acc={tree['test_metrics']['accuracy']:.4f} */")
    L.append(f"#define HCS_TREE_NODES {n}")
    L.append(arr("int    HCS_TREE_LEFT[HCS_TREE_NODES]", tree["children_left"], lambda v: str(int(v))))
    L.append(arr("int    HCS_TREE_RIGHT[HCS_TREE_NODES]", tree["children_right"], lambda v: str(int(v))))
    L.append(arr("int    HCS_TREE_FEAT[HCS_TREE_NODES]", tree["feature"], lambda v: str(int(v))))
    L.append(arr("double HCS_TREE_THRESH[HCS_TREE_NODES]", tree["threshold"], cd))
    L.append(arr("int    HCS_TREE_CLASS[HCS_TREE_NODES]", tree["leaf_class"], lambda v: str(int(v))))
    L.append("")
    L.append("""void hcs_classifier_init(hcs_fft_classifier_t *c, hcs_clf_mode_t mode)
{
  c->next_idx = 0;
  c->count = 0;
  c->mode = mode;
}

void hcs_classifier_set_mode(hcs_fft_classifier_t *c, hcs_clf_mode_t mode)
{
  c->mode = mode;
}

void hcs_classifier_push(hcs_fft_classifier_t *c, double fft_us)
{
  c->buf[c->next_idx % HCS_FFT_WINDOW] = fft_us;
  c->next_idx++;
  if (c->count < HCS_FFT_WINDOW) c->count++;
}

hcs_fft_feats_t hcs_classifier_feats(const hcs_fft_classifier_t *c)
{
  hcs_fft_feats_t f = { NAN, 0.0, 0.0, 0.0 };
  if (c->count <= 0) return f;
  int start = c->next_idx - c->count;
  double sum = 0.0;
  for (int k = 0; k < c->count; k++) {
    int p = (start + k) % HCS_FFT_WINDOW; if (p < 0) p += HCS_FFT_WINDOW;
    sum += c->buf[p];
  }
  double mean = sum / (double)c->count;
  double m2 = 0.0, m3 = 0.0, m4 = 0.0;
  for (int k = 0; k < c->count; k++) {
    int p = (start + k) % HCS_FFT_WINDOW; if (p < 0) p += HCS_FFT_WINDOW;
    double d = c->buf[p] - mean, d2 = d * d;
    m2 += d2; m3 += d2 * d; m4 += d2 * d2;
  }
  m2 /= c->count; m3 /= c->count; m4 /= c->count;
  f.mean = mean;
  f.std = sqrt(m2);
  if (m2 > 1e-12 && c->count >= 2) {
    f.skew = m3 / pow(m2, 1.5);
    f.kurt = m4 / (m2 * m2) - 3.0;
  }
  return f;
}

static int digitize3(double x)
{
  int s = 0;
  for (int i = 0; i < 3; i++) if (x >= HCS_FFT_THRESHOLDS[i]) s++;   /* np.digitize right=False */
  return s;
}

static int tree_classify(const double *feats)
{
  int node = 0;
  while (HCS_TREE_LEFT[node] >= 0)
    node = (feats[HCS_TREE_FEAT[node]] <= HCS_TREE_THRESH[node])
             ? HCS_TREE_LEFT[node] : HCS_TREE_RIGHT[node];
  return HCS_TREE_CLASS[node];
}

int hcs_classifier_interf_mode(const hcs_fft_classifier_t *c, hcs_clf_mode_t mode)
{
  if (c->count <= 0) return -1;
  hcs_fft_feats_t f = hcs_classifier_feats(c);
  if (mode == HCS_CLF_TREE) {
    double feats[4] = { f.mean, f.std, f.skew, f.kurt };
    return tree_classify(feats);
  }
  return digitize3(f.mean);
}

int hcs_classifier_interf(const hcs_fft_classifier_t *c)
{
  return hcs_classifier_interf_mode(c, c->mode);
}

const char *hcs_interf_name(int interf)
{
  switch (interf) {
    case HCS_INTERF_NO_CACHE: return "NO_CACHE";
    case HCS_INTERF_LOW:      return "LOW";
    case HCS_INTERF_MED:      return "MED";
    case HCS_INTERF_XXHIGH:   return "XXHIGH";
    default:                  return "UNKNOWN";
  }
}

const char *hcs_clf_mode_name(hcs_clf_mode_t mode)
{
  return mode == HCS_CLF_TREE ? "TREE[mean,std,skew,kurt]" : "MEAN_THRESHOLD";
}
""")
    L.append("hcs_state_t hcs_interf_to_state(int interf)")
    L.append("{")
    L.append("  switch (interf) {")
    for interf in INTERF_ORDER:
        mapped = map_interf_to_state(interf, predictor_states)
        note = "" if mapped == interf else f"  /* {interf} 无模型 -> 保守映射 {mapped} */"
        L.append(f"    case HCS_INTERF_{interf}: return {state_enum(mapped)};{note}")
    L.append("    default: return HCS_STATE_COUNT;")
    L.append("  }")
    L.append("}")
    return "\n".join(L) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description="export FFT classifier (2 modes) -> hcs_state_classifier.h/.c")
    ap.add_argument("--threshold-json", default="python_scripts/fft_state_model_out_w20/threshold_model.json")
    ap.add_argument("--tree-json", default="python_scripts/fft_state_model_out_w20/fft_tree_model.json")
    ap.add_argument("--predictor-json", default="python_scripts/hcs_model_out/hcs_model.json")
    ap.add_argument("--out-dir", default="openair2/LAYER2/NR_MAC_gNB")
    args = ap.parse_args()

    thr_model = json.loads(Path(args.threshold_json).read_text(encoding="utf-8"))
    if thr_model.get("model_type") != "ordered_threshold":
        raise ValueError(f"expected ordered_threshold, got {thr_model.get('model_type')}")
    window = parse_window(thr_model["feature"])
    thresholds = list(thr_model["thresholds"])

    tree = json.loads(Path(args.tree_json).read_text(encoding="utf-8"))
    if tree.get("model_type") != "fft_decision_tree":
        raise ValueError(f"expected fft_decision_tree, got {tree.get('model_type')}")
    if tree["feature_order"] != TREE_FEATURES:
        raise ValueError(f"tree feature_order {tree['feature_order']} != C hardcoded {TREE_FEATURES}")
    if int(tree["window"]) != window:
        raise ValueError(f"window mismatch: threshold w{window} vs tree w{tree['window']}")

    predictor_states = json.loads(Path(args.predictor_json).read_text(encoding="utf-8"))["states"]

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "hcs_state_classifier.h").write_text(gen_header(window), encoding="utf-8")
    (out / "hcs_state_classifier.c").write_text(gen_source(thresholds, tree, predictor_states), encoding="utf-8")
    print(f"window={window}")
    print(f"mode A (mean threshold): thresholds={thresholds}")
    print(f"mode B (tree {tree['feature_order']}): nodes={tree['n_nodes']} acc={tree['test_metrics']['accuracy']:.4f}")
    print(f"interf->state: " + ", ".join(
        f"{i}->{map_interf_to_state(i, predictor_states)}" for i in INTERF_ORDER))
    print(f"wrote: {out/'hcs_state_classifier.h'}\n       {out/'hcs_state_classifier.c'}")


if __name__ == "__main__":
    main()
