/* hcs_state_classifier.c —— Auto-generated by export_fft_classifier_to_c.py. DO NOT EDIT. */
#include "hcs_state_classifier.h"
#include <math.h>

static const double HCS_FFT_THRESHOLDS[3] = { 42.763138354430382, 47.085137468354432, 47.634114430379753 };

/* mode B: 浅决策树 (feats order = ['mean', 'std', 'skew', 'kurt']), acc=0.9461 */
#define HCS_TREE_NODES 31
static const int    HCS_TREE_LEFT[HCS_TREE_NODES] = { 1, 2, 3, 4, -1, -1, 7, -1, -1, 10, 11, -1, -1, 14, -1, -1, 17, 18, 19, -1, -1, 22, -1, -1, 25, 26, -1, -1, 29, -1, -1 };
static const int    HCS_TREE_RIGHT[HCS_TREE_NODES] = { 16, 9, 6, 5, -1, -1, 8, -1, -1, 13, 12, -1, -1, 15, -1, -1, 24, 21, 20, -1, -1, 23, -1, -1, 28, 27, -1, -1, 30, -1, -1 };
static const int    HCS_TREE_FEAT[HCS_TREE_NODES] = { 0, 1, 1, 2, -2, -2, 2, -2, -2, 3, 1, -2, -2, 3, -2, -2, 0, 1, 1, -2, -2, 3, -2, -2, 1, 0, -2, -2, 2, -2, -2 };
static const double HCS_TREE_THRESH[HCS_TREE_NODES] = { 42.763750076293945, 1.0056754946708679, 0.8844245970249176, 3.197425365447998, -2, -2, 1.2186987996101379, -2, -2, 7.56777024269104, 1.3748216032981873, -2, -2, 9.991340160369873, -2, -2, 47.53325080871582, 3.7776108980178833, 1.9929081797599792, -2, -2, 5.371673583984375, -2, -2, 4.3554275035858154, 48.797500610351562, -2, -2, 0.76931166648864746, -2, -2 };
static const int    HCS_TREE_CLASS[HCS_TREE_NODES] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 3, 3, 3, 3, 3, 3, 3 };

void hcs_classifier_init(hcs_fft_classifier_t *c, hcs_clf_mode_t mode)
{
  c->next_idx = 0;
  c->count = 0;
  c->mode = mode;
}

void hcs_classifier_set_mode(hcs_fft_classifier_t *c, hcs_clf_mode_t mode)
{
  c->mode = mode;
}

void hcs_classifier_push(hcs_fft_classifier_t *c, double fft_us)
{
  c->buf[c->next_idx % HCS_FFT_WINDOW] = fft_us;
  c->next_idx++;
  if (c->count < HCS_FFT_WINDOW) c->count++;
}

hcs_fft_feats_t hcs_classifier_feats(const hcs_fft_classifier_t *c)
{
  hcs_fft_feats_t f = { NAN, 0.0, 0.0, 0.0 };
  if (c->count <= 0) return f;
  int start = c->next_idx - c->count;
  double sum = 0.0;
  for (int k = 0; k < c->count; k++) {
    int p = (start + k) % HCS_FFT_WINDOW; if (p < 0) p += HCS_FFT_WINDOW;
    sum += c->buf[p];
  }
  double mean = sum / (double)c->count;
  double m2 = 0.0, m3 = 0.0, m4 = 0.0;
  for (int k = 0; k < c->count; k++) {
    int p = (start + k) % HCS_FFT_WINDOW; if (p < 0) p += HCS_FFT_WINDOW;
    double d = c->buf[p] - mean, d2 = d * d;
    m2 += d2; m3 += d2 * d; m4 += d2 * d2;
  }
  m2 /= c->count; m3 /= c->count; m4 /= c->count;
  f.mean = mean;
  f.std = sqrt(m2);
  if (m2 > 1e-12 && c->count >= 2) {
    f.skew = m3 / pow(m2, 1.5);
    f.kurt = m4 / (m2 * m2) - 3.0;
  }
  return f;
}

static int digitize3(double x)
{
  int s = 0;
  for (int i = 0; i < 3; i++) if (x >= HCS_FFT_THRESHOLDS[i]) s++;   /* np.digitize right=False */
  return s;
}

static int tree_classify(const double *feats)
{
  int node = 0;
  while (HCS_TREE_LEFT[node] >= 0)
    node = (feats[HCS_TREE_FEAT[node]] <= HCS_TREE_THRESH[node])
             ? HCS_TREE_LEFT[node] : HCS_TREE_RIGHT[node];
  return HCS_TREE_CLASS[node];
}

int hcs_classifier_interf_mode(const hcs_fft_classifier_t *c, hcs_clf_mode_t mode)
{
  if (c->count <= 0) return -1;
  hcs_fft_feats_t f = hcs_classifier_feats(c);
  if (mode == HCS_CLF_TREE) {
    double feats[4] = { f.mean, f.std, f.skew, f.kurt };
    return tree_classify(feats);
  }
  return digitize3(f.mean);
}

int hcs_classifier_interf(const hcs_fft_classifier_t *c)
{
  return hcs_classifier_interf_mode(c, c->mode);
}

const char *hcs_interf_name(int interf)
{
  switch (interf) {
    case HCS_INTERF_NO_CACHE: return "NO_CACHE";
    case HCS_INTERF_LOW:      return "LOW";
    case HCS_INTERF_MED:      return "MED";
    case HCS_INTERF_XXHIGH:   return "XXHIGH";
    default:                  return "UNKNOWN";
  }
}

const char *hcs_clf_mode_name(hcs_clf_mode_t mode)
{
  return mode == HCS_CLF_TREE ? "TREE[mean,std,skew,kurt]" : "MEAN_THRESHOLD";
}

hcs_state_t hcs_interf_to_state(int interf)
{
  switch (interf) {
    case HCS_INTERF_NO_CACHE: return HCS_STATE_NO_CACHE;
    case HCS_INTERF_LOW: return HCS_STATE_LOW;
    case HCS_INTERF_MED: return HCS_STATE_XXHIGH;  /* MED 无模型 -> 保守映射 XXHIGH */
    case HCS_INTERF_XXHIGH: return HCS_STATE_XXHIGH;
    default: return HCS_STATE_COUNT;
  }
}
