/* hcs_state_classifier.h —— Auto-generated by export_fft_classifier_to_c.py. DO NOT EDIT.
 * FFT 时延 -> 争用 state 分类器 (plan 组件 ③/2a). 两版运行时可切换 (见 hcs_clf_mode_t).
 */
#ifndef HCS_STATE_CLASSIFIER_H
#define HCS_STATE_CLASSIFIER_H

#include "hcs_model.h"   /* hcs_state_t */

#ifdef __cplusplus
extern "C" {
#endif

enum { HCS_INTERF_NO_CACHE = 0, HCS_INTERF_LOW = 1, HCS_INTERF_MED = 2,
       HCS_INTERF_XXHIGH = 3, HCS_INTERF_COUNT = 4 };

/* 运行时可切换的分类方法 */
typedef enum {
  HCS_CLF_MEAN_THRESHOLD = 0,   /* mode A: 窗口均值 + 阈值 */
  HCS_CLF_TREE           = 1    /* mode B: [mean,std,skew,kurt] 浅决策树 */
} hcs_clf_mode_t;

#define HCS_FFT_WINDOW 20

typedef struct {
  double buf[HCS_FFT_WINDOW];   /* 最近 W 个 slot 的 FFT 时延 (µs) */
  int next_idx;                 /* 下一个写入位置 (单调递增取模) */
  int count;                    /* 已填入样本数 (<= W) */
  hcs_clf_mode_t mode;          /* 当前分类方法; 可随时切换对比 */
} hcs_fft_classifier_t;

typedef struct { double mean, std, skew, kurt; } hcs_fft_feats_t;

void            hcs_classifier_init(hcs_fft_classifier_t *c, hcs_clf_mode_t mode);
void            hcs_classifier_set_mode(hcs_fft_classifier_t *c, hcs_clf_mode_t mode);
void            hcs_classifier_push(hcs_fft_classifier_t *c, double fft_us);  /* 每 slot 推入 */
hcs_fft_feats_t hcs_classifier_feats(const hcs_fft_classifier_t *c);          /* 窗口矩特征 */
int             hcs_classifier_interf_mode(const hcs_fft_classifier_t *c, hcs_clf_mode_t mode);
int             hcs_classifier_interf(const hcs_fft_classifier_t *c);   /* 按 c->mode 分发; 空->-1 */
const char     *hcs_interf_name(int interf);
const char     *hcs_clf_mode_name(hcs_clf_mode_t mode);
hcs_state_t     hcs_interf_to_state(int interf);   /* 4-class -> 预测器 3-state */

#ifdef __cplusplus
}
#endif

#endif /* HCS_STATE_CLASSIFIER_H */
